// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: protobuf/service/coupon_service.proto

package service

import (
	entity "github.com/Sujin1135/coupon-service-interface/protobuf/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateCampaignRequest) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CreateCampaignRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateCampaignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*CreateCampaignResponse_Data_
	//	*CreateCampaignResponse_Error_
	Value         isCreateCampaignResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse) Reset() {
	*x = CreateCampaignResponse{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse) ProtoMessage() {}

func (x *CreateCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCampaignResponse) GetValue() isCreateCampaignResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateCampaignResponse) GetData() *CreateCampaignResponse_Data {
	if x != nil {
		if x, ok := x.Value.(*CreateCampaignResponse_Data_); ok {
			return x.Data
		}
	}
	return nil
}

func (x *CreateCampaignResponse) GetError() *CreateCampaignResponse_Error {
	if x != nil {
		if x, ok := x.Value.(*CreateCampaignResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateCampaignResponse_Value interface {
	isCreateCampaignResponse_Value()
}

type CreateCampaignResponse_Data_ struct {
	Data *CreateCampaignResponse_Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type CreateCampaignResponse_Error_ struct {
	Error *CreateCampaignResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateCampaignResponse_Data_) isCreateCampaignResponse_Value() {}

func (*CreateCampaignResponse_Error_) isCreateCampaignResponse_Value() {}

type IssueCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponRequest) Reset() {
	*x = IssueCouponRequest{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponRequest) ProtoMessage() {}

func (x *IssueCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponRequest.ProtoReflect.Descriptor instead.
func (*IssueCouponRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{2}
}

func (x *IssueCouponRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *IssueCouponRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IssueCouponResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*IssueCouponResponse_Data_
	//	*IssueCouponResponse_Error_
	Value         isIssueCouponResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponResponse) Reset() {
	*x = IssueCouponResponse{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponResponse) ProtoMessage() {}

func (x *IssueCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponResponse.ProtoReflect.Descriptor instead.
func (*IssueCouponResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{3}
}

func (x *IssueCouponResponse) GetValue() isIssueCouponResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *IssueCouponResponse) GetData() *IssueCouponResponse_Data {
	if x != nil {
		if x, ok := x.Value.(*IssueCouponResponse_Data_); ok {
			return x.Data
		}
	}
	return nil
}

func (x *IssueCouponResponse) GetError() *IssueCouponResponse_Error {
	if x != nil {
		if x, ok := x.Value.(*IssueCouponResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isIssueCouponResponse_Value interface {
	isIssueCouponResponse_Value()
}

type IssueCouponResponse_Data_ struct {
	Data *IssueCouponResponse_Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type IssueCouponResponse_Error_ struct {
	Error *IssueCouponResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*IssueCouponResponse_Data_) isIssueCouponResponse_Value() {}

func (*IssueCouponResponse_Error_) isIssueCouponResponse_Value() {}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCampaignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*GetCampaignResponse_Data_
	//	*GetCampaignResponse_Error_
	Value         isGetCampaignResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse) Reset() {
	*x = GetCampaignResponse{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse) ProtoMessage() {}

func (x *GetCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCampaignResponse) GetValue() isGetCampaignResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetCampaignResponse) GetData() *GetCampaignResponse_Data {
	if x != nil {
		if x, ok := x.Value.(*GetCampaignResponse_Data_); ok {
			return x.Data
		}
	}
	return nil
}

func (x *GetCampaignResponse) GetError() *GetCampaignResponse_Error {
	if x != nil {
		if x, ok := x.Value.(*GetCampaignResponse_Error_); ok {
			return x.Error
		}
	}
	return nil
}

type isGetCampaignResponse_Value interface {
	isGetCampaignResponse_Value()
}

type GetCampaignResponse_Data_ struct {
	Data *GetCampaignResponse_Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type GetCampaignResponse_Error_ struct {
	Error *GetCampaignResponse_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetCampaignResponse_Data_) isGetCampaignResponse_Value() {}

func (*GetCampaignResponse_Error_) isGetCampaignResponse_Value() {}

type CreateCampaignResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *entity.Campaign       `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse_Data) Reset() {
	*x = CreateCampaignResponse_Data{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse_Data) ProtoMessage() {}

func (x *CreateCampaignResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse_Data.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse_Data) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *CreateCampaignResponse_Data) GetCampaign() *entity.Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type CreateCampaignResponse_Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*CreateCampaignResponse_Error_BadRequest
	//	*CreateCampaignResponse_Error_InternalProblem
	Error         isCreateCampaignResponse_Error_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignResponse_Error) Reset() {
	*x = CreateCampaignResponse_Error{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignResponse_Error) ProtoMessage() {}

func (x *CreateCampaignResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignResponse_Error.ProtoReflect.Descriptor instead.
func (*CreateCampaignResponse_Error) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{1, 1}
}

func (x *CreateCampaignResponse_Error) GetError() isCreateCampaignResponse_Error_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateCampaignResponse_Error) GetBadRequest() *entity.BadRequestError {
	if x != nil {
		if x, ok := x.Error.(*CreateCampaignResponse_Error_BadRequest); ok {
			return x.BadRequest
		}
	}
	return nil
}

func (x *CreateCampaignResponse_Error) GetInternalProblem() *entity.InternalError {
	if x != nil {
		if x, ok := x.Error.(*CreateCampaignResponse_Error_InternalProblem); ok {
			return x.InternalProblem
		}
	}
	return nil
}

type isCreateCampaignResponse_Error_Error interface {
	isCreateCampaignResponse_Error_Error()
}

type CreateCampaignResponse_Error_BadRequest struct {
	BadRequest *entity.BadRequestError `protobuf:"bytes,1,opt,name=bad_request,json=badRequest,proto3,oneof"`
}

type CreateCampaignResponse_Error_InternalProblem struct {
	InternalProblem *entity.InternalError `protobuf:"bytes,2,opt,name=internal_problem,json=internalProblem,proto3,oneof"`
}

func (*CreateCampaignResponse_Error_BadRequest) isCreateCampaignResponse_Error_Error() {}

func (*CreateCampaignResponse_Error_InternalProblem) isCreateCampaignResponse_Error_Error() {}

type IssueCouponResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponResponse_Data) Reset() {
	*x = IssueCouponResponse_Data{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponResponse_Data) ProtoMessage() {}

func (x *IssueCouponResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponResponse_Data.ProtoReflect.Descriptor instead.
func (*IssueCouponResponse_Data) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *IssueCouponResponse_Data) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type IssueCouponResponse_Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*IssueCouponResponse_Error_NotFound
	//	*IssueCouponResponse_Error_BadRequest
	//	*IssueCouponResponse_Error_InternalProblem
	Error         isIssueCouponResponse_Error_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCouponResponse_Error) Reset() {
	*x = IssueCouponResponse_Error{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCouponResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCouponResponse_Error) ProtoMessage() {}

func (x *IssueCouponResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCouponResponse_Error.ProtoReflect.Descriptor instead.
func (*IssueCouponResponse_Error) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{3, 1}
}

func (x *IssueCouponResponse_Error) GetError() isIssueCouponResponse_Error_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *IssueCouponResponse_Error) GetNotFound() *entity.NotFoundError {
	if x != nil {
		if x, ok := x.Error.(*IssueCouponResponse_Error_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

func (x *IssueCouponResponse_Error) GetBadRequest() *entity.BadRequestError {
	if x != nil {
		if x, ok := x.Error.(*IssueCouponResponse_Error_BadRequest); ok {
			return x.BadRequest
		}
	}
	return nil
}

func (x *IssueCouponResponse_Error) GetInternalProblem() *entity.InternalError {
	if x != nil {
		if x, ok := x.Error.(*IssueCouponResponse_Error_InternalProblem); ok {
			return x.InternalProblem
		}
	}
	return nil
}

type isIssueCouponResponse_Error_Error interface {
	isIssueCouponResponse_Error_Error()
}

type IssueCouponResponse_Error_NotFound struct {
	NotFound *entity.NotFoundError `protobuf:"bytes,1,opt,name=not_found,json=notFound,proto3,oneof"`
}

type IssueCouponResponse_Error_BadRequest struct {
	BadRequest *entity.BadRequestError `protobuf:"bytes,2,opt,name=bad_request,json=badRequest,proto3,oneof"`
}

type IssueCouponResponse_Error_InternalProblem struct {
	InternalProblem *entity.InternalError `protobuf:"bytes,3,opt,name=internal_problem,json=internalProblem,proto3,oneof"`
}

func (*IssueCouponResponse_Error_NotFound) isIssueCouponResponse_Error_Error() {}

func (*IssueCouponResponse_Error_BadRequest) isIssueCouponResponse_Error_Error() {}

func (*IssueCouponResponse_Error_InternalProblem) isIssueCouponResponse_Error_Error() {}

type GetCampaignResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *entity.Campaign       `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse_Data) Reset() {
	*x = GetCampaignResponse_Data{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse_Data) ProtoMessage() {}

func (x *GetCampaignResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse_Data.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse_Data) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetCampaignResponse_Data) GetCampaign() *entity.Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type GetCampaignResponse_Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Error:
	//
	//	*GetCampaignResponse_Error_NotFound
	Error         isGetCampaignResponse_Error_Error `protobuf_oneof:"error"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignResponse_Error) Reset() {
	*x = GetCampaignResponse_Error{}
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignResponse_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignResponse_Error) ProtoMessage() {}

func (x *GetCampaignResponse_Error) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_service_coupon_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignResponse_Error.ProtoReflect.Descriptor instead.
func (*GetCampaignResponse_Error) Descriptor() ([]byte, []int) {
	return file_protobuf_service_coupon_service_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetCampaignResponse_Error) GetError() isGetCampaignResponse_Error_Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetCampaignResponse_Error) GetNotFound() *entity.NotFoundError {
	if x != nil {
		if x, ok := x.Error.(*GetCampaignResponse_Error_NotFound); ok {
			return x.NotFound
		}
	}
	return nil
}

type isGetCampaignResponse_Error_Error interface {
	isGetCampaignResponse_Error_Error()
}

type GetCampaignResponse_Error_NotFound struct {
	NotFound *entity.NotFoundError `protobuf:"bytes,1,opt,name=not_found,json=notFound,proto3,oneof"`
}

func (*GetCampaignResponse_Error_NotFound) isGetCampaignResponse_Error_Error() {}

var File_protobuf_service_coupon_service_proto protoreflect.FileDescriptor

var file_protobuf_service_coupon_service_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x63, 0x6f, 0x75, 0x70,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a,
	0x09, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x69, 0x73,
	0x73, 0x75, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65,
	0x73, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41,
	0x74, 0x22, 0xf6, 0x02, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x69, 0x6f, 0x2e,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x47, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2f, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x3f, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x1a, 0x82, 0x01, 0x0a,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x61, 0x64, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x0a, 0x62, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x10, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x12, 0x49, 0x73,
	0x73, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xfb, 0x02, 0x0a, 0x13, 0x49,
	0x73, 0x73, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x44, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x1e, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0xb1, 0x01, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4e, 0x6f, 0x74, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x61, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x62,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x10, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x50,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xa9, 0x02, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69,
	0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f,
	0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x44, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x69,
	0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x1a, 0x3f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x08, 0x63,
	0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x08, 0x63, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x1a, 0x3f, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x2d, 0x0a,
	0x09, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x08, 0x6e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x07, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xb1,
	0x02, 0x0a, 0x0c, 0x47, 0x72, 0x65, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x65, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67,
	0x6e, 0x12, 0x28, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70,
	0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x69, 0x6f,
	0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0b, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43,
	0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x69,
	0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x43, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x12, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x69, 0x6f, 0x2e,
	0x63, 0x6f, 0x75, 0x70, 0x6f, 0x6e, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x6d, 0x70, 0x61, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x53, 0x75, 0x6a, 0x69, 0x6e, 0x31, 0x31, 0x33, 0x35, 0x2f, 0x63, 0x6f, 0x75, 0x70, 0x6f,
	0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protobuf_service_coupon_service_proto_rawDescOnce sync.Once
	file_protobuf_service_coupon_service_proto_rawDescData []byte
)

func file_protobuf_service_coupon_service_proto_rawDescGZIP() []byte {
	file_protobuf_service_coupon_service_proto_rawDescOnce.Do(func() {
		file_protobuf_service_coupon_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_service_coupon_service_proto_rawDesc), len(file_protobuf_service_coupon_service_proto_rawDesc)))
	})
	return file_protobuf_service_coupon_service_proto_rawDescData
}

var file_protobuf_service_coupon_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protobuf_service_coupon_service_proto_goTypes = []any{
	(*CreateCampaignRequest)(nil),        // 0: io.coupon.service.CreateCampaignRequest
	(*CreateCampaignResponse)(nil),       // 1: io.coupon.service.CreateCampaignResponse
	(*IssueCouponRequest)(nil),           // 2: io.coupon.service.IssueCouponRequest
	(*IssueCouponResponse)(nil),          // 3: io.coupon.service.IssueCouponResponse
	(*GetCampaignRequest)(nil),           // 4: io.coupon.service.GetCampaignRequest
	(*GetCampaignResponse)(nil),          // 5: io.coupon.service.GetCampaignResponse
	(*CreateCampaignResponse_Data)(nil),  // 6: io.coupon.service.CreateCampaignResponse.Data
	(*CreateCampaignResponse_Error)(nil), // 7: io.coupon.service.CreateCampaignResponse.Error
	(*IssueCouponResponse_Data)(nil),     // 8: io.coupon.service.IssueCouponResponse.Data
	(*IssueCouponResponse_Error)(nil),    // 9: io.coupon.service.IssueCouponResponse.Error
	(*GetCampaignResponse_Data)(nil),     // 10: io.coupon.service.GetCampaignResponse.Data
	(*GetCampaignResponse_Error)(nil),    // 11: io.coupon.service.GetCampaignResponse.Error
	(*timestamppb.Timestamp)(nil),        // 12: google.protobuf.Timestamp
	(*entity.Campaign)(nil),              // 13: io.coupon.service.Campaign
	(*entity.BadRequestError)(nil),       // 14: BadRequestError
	(*entity.InternalError)(nil),         // 15: InternalError
	(*entity.NotFoundError)(nil),         // 16: NotFoundError
}
var file_protobuf_service_coupon_service_proto_depIdxs = []int32{
	12, // 0: io.coupon.service.CreateCampaignRequest.issued_at:type_name -> google.protobuf.Timestamp
	12, // 1: io.coupon.service.CreateCampaignRequest.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 2: io.coupon.service.CreateCampaignResponse.data:type_name -> io.coupon.service.CreateCampaignResponse.Data
	7,  // 3: io.coupon.service.CreateCampaignResponse.error:type_name -> io.coupon.service.CreateCampaignResponse.Error
	8,  // 4: io.coupon.service.IssueCouponResponse.data:type_name -> io.coupon.service.IssueCouponResponse.Data
	9,  // 5: io.coupon.service.IssueCouponResponse.error:type_name -> io.coupon.service.IssueCouponResponse.Error
	10, // 6: io.coupon.service.GetCampaignResponse.data:type_name -> io.coupon.service.GetCampaignResponse.Data
	11, // 7: io.coupon.service.GetCampaignResponse.error:type_name -> io.coupon.service.GetCampaignResponse.Error
	13, // 8: io.coupon.service.CreateCampaignResponse.Data.campaign:type_name -> io.coupon.service.Campaign
	14, // 9: io.coupon.service.CreateCampaignResponse.Error.bad_request:type_name -> BadRequestError
	15, // 10: io.coupon.service.CreateCampaignResponse.Error.internal_problem:type_name -> InternalError
	16, // 11: io.coupon.service.IssueCouponResponse.Error.not_found:type_name -> NotFoundError
	14, // 12: io.coupon.service.IssueCouponResponse.Error.bad_request:type_name -> BadRequestError
	15, // 13: io.coupon.service.IssueCouponResponse.Error.internal_problem:type_name -> InternalError
	13, // 14: io.coupon.service.GetCampaignResponse.Data.campaign:type_name -> io.coupon.service.Campaign
	16, // 15: io.coupon.service.GetCampaignResponse.Error.not_found:type_name -> NotFoundError
	0,  // 16: io.coupon.service.GreetService.CreateCampaign:input_type -> io.coupon.service.CreateCampaignRequest
	2,  // 17: io.coupon.service.GreetService.IssueCoupon:input_type -> io.coupon.service.IssueCouponRequest
	4,  // 18: io.coupon.service.GreetService.GetCampaign:input_type -> io.coupon.service.GetCampaignRequest
	1,  // 19: io.coupon.service.GreetService.CreateCampaign:output_type -> io.coupon.service.CreateCampaignResponse
	3,  // 20: io.coupon.service.GreetService.IssueCoupon:output_type -> io.coupon.service.IssueCouponResponse
	5,  // 21: io.coupon.service.GreetService.GetCampaign:output_type -> io.coupon.service.GetCampaignResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_protobuf_service_coupon_service_proto_init() }
func file_protobuf_service_coupon_service_proto_init() {
	if File_protobuf_service_coupon_service_proto != nil {
		return
	}
	file_protobuf_service_coupon_service_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateCampaignResponse_Data_)(nil),
		(*CreateCampaignResponse_Error_)(nil),
	}
	file_protobuf_service_coupon_service_proto_msgTypes[3].OneofWrappers = []any{
		(*IssueCouponResponse_Data_)(nil),
		(*IssueCouponResponse_Error_)(nil),
	}
	file_protobuf_service_coupon_service_proto_msgTypes[5].OneofWrappers = []any{
		(*GetCampaignResponse_Data_)(nil),
		(*GetCampaignResponse_Error_)(nil),
	}
	file_protobuf_service_coupon_service_proto_msgTypes[7].OneofWrappers = []any{
		(*CreateCampaignResponse_Error_BadRequest)(nil),
		(*CreateCampaignResponse_Error_InternalProblem)(nil),
	}
	file_protobuf_service_coupon_service_proto_msgTypes[9].OneofWrappers = []any{
		(*IssueCouponResponse_Error_NotFound)(nil),
		(*IssueCouponResponse_Error_BadRequest)(nil),
		(*IssueCouponResponse_Error_InternalProblem)(nil),
	}
	file_protobuf_service_coupon_service_proto_msgTypes[11].OneofWrappers = []any{
		(*GetCampaignResponse_Error_NotFound)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_service_coupon_service_proto_rawDesc), len(file_protobuf_service_coupon_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_service_coupon_service_proto_goTypes,
		DependencyIndexes: file_protobuf_service_coupon_service_proto_depIdxs,
		MessageInfos:      file_protobuf_service_coupon_service_proto_msgTypes,
	}.Build()
	File_protobuf_service_coupon_service_proto = out.File
	file_protobuf_service_coupon_service_proto_goTypes = nil
	file_protobuf_service_coupon_service_proto_depIdxs = nil
}
