// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: protobuf/entity/coupon.proto

package entity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IssueAmount   int64                  `protobuf:"varint,3,opt,name=issue_amount,json=issueAmount,proto3" json:"issue_amount,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IssuedCoupons []*IssuedCoupon        `protobuf:"bytes,6,rep,name=issued_coupons,json=issuedCoupons,proto3" json:"issued_coupons,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_protobuf_entity_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetIssueAmount() int64 {
	if x != nil {
		return x.IssueAmount
	}
	return 0
}

func (x *Campaign) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Campaign) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Campaign) GetIssuedCoupons() []*IssuedCoupon {
	if x != nil {
		return x.IssuedCoupons
	}
	return nil
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Campaign) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type IssuedCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CouponId      string                 `protobuf:"bytes,2,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuedCoupon) Reset() {
	*x = IssuedCoupon{}
	mi := &file_protobuf_entity_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedCoupon) ProtoMessage() {}

func (x *IssuedCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_entity_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedCoupon.ProtoReflect.Descriptor instead.
func (*IssuedCoupon) Descriptor() ([]byte, []int) {
	return file_protobuf_entity_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *IssuedCoupon) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IssuedCoupon) GetCouponId() string {
	if x != nil {
		return x.CouponId
	}
	return ""
}

func (x *IssuedCoupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *IssuedCoupon) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *IssuedCoupon) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

var File_protobuf_entity_coupon_proto protoreflect.FileDescriptor

const file_protobuf_entity_coupon_proto_rawDesc = "" +
	"\n" +
	"\x1cprotobuf/entity/coupon.proto\x12\x11io.coupon.service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x03\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fissue_amount\x18\x03 \x01(\x03R\vissueAmount\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12F\n" +
	"\x0eissued_coupons\x18\x06 \x03(\v2\x1f.io.coupon.service.IssuedCouponR\rissuedCoupons\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"\xc7\x01\n" +
	"\fIssuedCoupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcoupon_id\x18\x02 \x01(\tR\bcouponId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAtB?Z=github.com/Sujin1135/coupon-service-interface/protobuf/entityb\x06proto3"

var (
	file_protobuf_entity_coupon_proto_rawDescOnce sync.Once
	file_protobuf_entity_coupon_proto_rawDescData []byte
)

func file_protobuf_entity_coupon_proto_rawDescGZIP() []byte {
	file_protobuf_entity_coupon_proto_rawDescOnce.Do(func() {
		file_protobuf_entity_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_entity_coupon_proto_rawDesc), len(file_protobuf_entity_coupon_proto_rawDesc)))
	})
	return file_protobuf_entity_coupon_proto_rawDescData
}

var file_protobuf_entity_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_entity_coupon_proto_goTypes = []any{
	(*Campaign)(nil),              // 0: io.coupon.service.Campaign
	(*IssuedCoupon)(nil),          // 1: io.coupon.service.IssuedCoupon
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_protobuf_entity_coupon_proto_depIdxs = []int32{
	2, // 0: io.coupon.service.Campaign.issued_at:type_name -> google.protobuf.Timestamp
	2, // 1: io.coupon.service.Campaign.expires_at:type_name -> google.protobuf.Timestamp
	1, // 2: io.coupon.service.Campaign.issued_coupons:type_name -> io.coupon.service.IssuedCoupon
	2, // 3: io.coupon.service.Campaign.created_at:type_name -> google.protobuf.Timestamp
	2, // 4: io.coupon.service.Campaign.modified_at:type_name -> google.protobuf.Timestamp
	2, // 5: io.coupon.service.IssuedCoupon.created_at:type_name -> google.protobuf.Timestamp
	2, // 6: io.coupon.service.IssuedCoupon.modified_at:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_entity_coupon_proto_init() }
func file_protobuf_entity_coupon_proto_init() {
	if File_protobuf_entity_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_entity_coupon_proto_rawDesc), len(file_protobuf_entity_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_entity_coupon_proto_goTypes,
		DependencyIndexes: file_protobuf_entity_coupon_proto_depIdxs,
		MessageInfos:      file_protobuf_entity_coupon_proto_msgTypes,
	}.Build()
	File_protobuf_entity_coupon_proto = out.File
	file_protobuf_entity_coupon_proto_goTypes = nil
	file_protobuf_entity_coupon_proto_depIdxs = nil
}
